services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: FlowTransact.Transactions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    restart: unless-stopped

  transactions-api:
    build:
      context: .
      dockerfile: src/transactions-service/Transactions.Api/Dockerfile
    ports:
      - "5263:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=FlowTransact.Transactions;Username=postgres;Password=password"
      ConnectionStrings__RabbitMQ: "amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - postgres
      - rabbitmq

  payments-api:
    build:
      context: .
      dockerfile: src/payments-service/Payments.Api/Dockerfile
    ports:
      - "5264:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=FlowTransact.Payments;Username=postgres;Password=password"
      ConnectionStrings__RabbitMQ: "amqp://guest:guest@rabbitmq:5672"
      TransactionApi__BaseUrl: "http://transactions-api:8080"
    depends_on:
      - postgres
      - rabbitmq
      - transactions-api

volumes:
  postgres_data:
  rabbitmq_data:
  seq_data: